version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.25.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    network_mode: host
    # networks:
    #   transnetwork:
    #     aliases:
    #       - nginx
    volumes:
      - ./vod-cds.conf:/etc/nginx/vod-cds.conf.temp
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/data/vod_cache
      - ./ssl:/etc/nginx/ssl
      - ./logs/error.log:/etc/nginx/logs/error.log
    environment:
      - LMS=${LMS} #CORS LMS DOMAIN
      - CMS=${CMS} #CORS CMS DOMAIN

      - MAIN=${MAIN} #CACHE TARGET MAIN
      - BACKUP=${BACKUP} #CACHE TARGET BACKUP

      - LOCAL_IP=${LOCAL_IP} #CDS IP
      - LOCAL_DOMAIN=${LOCAL_DOMAIN} #CDS DOMAIN
    command: /bin/bash -c "envsubst '$${LMS} $${CMS} $${MAIN} $${BACKUP} $${LOCAL_IP} $${LOCAL_DOMAIN}' < /etc/nginx/vod-cds.conf.temp > /etc/nginx/vod-cds.conf && exec nginx -g 'daemon off;'"

  cds-node:
    container_name: cds-node
    image: kip9696/lgd-cds-node:latest
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CDS_NAME=${CDS_NAME}
      - CDS_LOCATION=${CDS_LOCATION}
      - CDS_TYPE=${CDS_TYPE}
      - CMS_HOST=${CMS_HOST}
      - LOCAL_IP=${LOCAL_IP} #CDS IP
      - LOCAL_DOMAIN=${LOCAL_DOMAIN} #CDS DOMAIN
      - PARENT_CDS_HOST=${PARENT_CDS_HOST}
# networks:
#   transnetwork:
#     external: false
